import { Ticket } from '@/types/type';

export const TICKETS: Ticket[] = [
  {
    id: '1',
    category: 'Bus',
    title: 'Réservation NUKAFU → ESAG-NDE',
    image: '/images/bus-img1.jpg',
    caption: 'Voyagez confortablement de Lomé à Kara avec notre service de bus rapide et sécurisé.',
    date: '2025-06-15',
    departureTime: '06:00',
    arrivalTime: '8:00',
    price: 500,
    availableSeats: 20,
    driver: 'Mrs. Gloros',
    slug: 'nukafu-esag-nde-juin-2025',
  },
  {
    id: '2',
    category: 'MiniBus',
    title: 'Réservation ESAG-NDE → HEDZRANAWOE',
    image: '/images/bus-card.jpg',
    caption: 'Voyagez confortablement de Lomé à Kara avec notre service de bus rapide et sécurisé.',
    date: '2025-06-16',
    departureTime: '18:30',
    arrivalTime: '20:00',
    price: 800,
    availableSeats: 15,
    driver: 'M. Kodjo Adjakly',
    slug: 'esag-nde-hedzanawoe-juin-2025',
  },
  {
    id: '3',
    category: 'Big Bus',
    title: 'Réservation ASSIGANME → ESAG-NDE ',
    image: '/images/bus-card2.jpg',
    caption: 'Voyagez confortablement de Lomé à Kara avec notre service de bus rapide et sécurisé.',
    date: '2025-06-17',
    departureTime: '7:00',
    arrivalTime: '8:00',
    price: 600,
    availableSeats: 30,
    driver: 'M. Emmanuel',
    slug: 'assiganme-esag-nde-juin-2025',
  },
  {
    id: '4',
    category: 'Bus',
    title: 'Réservation ESAG-NDE → Baguida',
    image: '/images/bus-img1.jpg',
    caption: 'Voyagez confortablement de Lomé à Kara avec notre service de bus rapide et sécurisé.',
    date: '2025-06-18',
    departureTime: '18:00',
    arrivalTime: '20:00',
    price: 500,
    availableSeats: 20,
    driver: 'M. AJAVON',
    slug: 'esag-nde-baguida-juin-2025',
  },
  {
    id: '5',
    category: 'MiniBus',
    title: 'Réservation ADIDOGOME → ESAG-NDE',
    image: '/images/bus-card.jpg',
    caption: 'Voyagez confortablement de Lomé à Kara avec notre service de bus rapide et sécurisé.',
    date: '2025-06-19',
    departureTime: '7:00',
    arrivalTime: '08:30',
    price: 300,
    availableSeats: 15,
    driver: 'M. Yann AGB',
    slug: 'adidogome-esag-nde-juin-2025',
  },
];
